public class Tests{
    public static void main(String[] args){
        double score1 = 67.67;
        double score2 = 89.89;
        double score3 = 90.10;
        double average = ((score1 + score2 + score3)/3);
        System.out.print("Test Score 1: ");
        System.out.println(score1);
        System.out.print("Test Score 2: ");
        System.out.println(score2);
        System.out.print("Test Score 3: ");
        System.out.println(score3);
        System.out.print("The average of the 3 test scores is: ");
        System.out.print(average);
    }
}